# Generated by Django 3.1.2 on 2020-10-27 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_product_productprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 27, 4, 59, 6, 739693), null=True),
        ),
    ]
