# Generated by Django 3.1.2 on 2020-10-31 20:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201027_0545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField()),
                ('min_profit_per_hour', models.DecimalField(decimal_places=5, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='productprice',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 14, 37, 5, 34769), null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='machine',
            field=models.ManyToManyField(to='app.Machine'),
        ),
    ]
